### ISSUE TITLE
Question: I need freeimage to build correctly to android. Where you able to acomplish this with code in this repo?

### ISSUE THREAD

**Issue by MurkesM** [mlavik1/unity-async-textureimport-package#1]

**Comment by mlavik1** [comment]
Hi!
Yes, I tested with Unity 2021.2+, and the package here works fine: https://github.com/mlavik1/unity-async-textureimport-package/releases/tag/1.0

Do you need it for Unity 2022.2+ maybe? If so, I can try set up a build for that version too (should probably do that anyway).

**Comment by MurkesM** [comment]
Yeah I do. If you want to that would be great but I don't want to put you out or anything. I'm needing it soon for work as we are trying to get it to build to oculus 2 so I understand if you dont want to lol. Will what you currently have not work if we are on 2022.2? and if not is there a way I can bring it up to date? and lets say either you or I get it up to date do I just need to include it in my project or is there a special setup needed? I can probably just replace the freeimage dll in my project with the new version right?

**Comment by mlavik1** [comment]
Ok, no problem :) I'm glad to help!

Can you try the Unity-2022.2 package form this build and see if it works? https://github.com/mlavik1/unity-async-textureimport-package/actions/runs/3685186662

**Comment by mlavik1** [comment]
And yes, simply replacing the binaries should work :) Not the DLL though (that's for Windows). But the libFreeImage.so files in:
- Assets/Plugins/FreeImage/Android/arm64-v8a
- Assets/Plugins/FreeImage/Android/armeabi-v7a
(I'm not sure which of them works on Oculus 2, but I suppose one of them should). Keep the old .meta files as they are, and make sure the correct platform is checked for each of them.

**Comment by MurkesM** [comment]
I wasn't about to get the package working with our specific implementation, plus we are already using https://github.com/Looooong/UnityAsyncImageLoader package for async texture loading. But I included the free image android files from this repo into the package we are using and it worked! Thanks so much, saved me tons of time!

**Comment by mlavik1** [comment]
That's good to hear! :) I'll publish a new release with these binaries soon.
I'll close this issue then. Have a great day!
